In [1]:
import numpy as np 
import pandas as pd

## Creatin A Data Frame

In [2]:
data = {
    "Name": ["John", "Anna", "Peter", "Linda"],
    "Age": [28, 34, 29, 42],
    "City": ["New York", "Paris", "Berlin", "London"],
    "Salary": [65000, 70000, 62000, 85000]
}

In [4]:
df=pd.DataFrame(data)

In [5]:
data_list = [
    ["John", 28, "New York", 65000],
    ["Anna", 34, "Paris", 70000],
    ["Peter", 29, "Berlin", 62000],
    ["Linda", 42, "London", 85000]
]

In [11]:
dfl=pd.DataFrame(data_list)
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selection And Indexing Of Columns

In [12]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

## Creating a new column

In [15]:
df2["Designation"]=["Dr.","Eng.","Dr.","Eng."]

In [16]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000         Dr.
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000         Dr.
3  Linda   42    London   85000        Eng.

## Removing new columns

In [21]:
df2=df2.drop('Designation',axis=1)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selecting Rows

In [22]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [24]:
df.loc[[0,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [25]:
df.iloc[[2,3]]

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

## Selecting Subsets of Rows and Columns

In [26]:
df.iloc[[2,3]][["City","Salary"]]

     City  Salary
2  Berlin   62000
3  London   85000

## Conditional Seletion

In [ ]:
#People who above age 30

In [27]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [30]:
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000