In [2]:
import numpy as np
import pandas as pd

## Finding Missing Data

In [7]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [5]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [6]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

## Removing Missing Data

In [8]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [10]:
df.dropna(thresh=3) # check non -null value

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

## Filling The Missing Data

In [11]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [12]:
values={'A':0,'B':100,'C':200,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  200.0  400.0
4  5.0  5  200.0    5.0